spring:
  application:
    name: registration-service
  #datasource:
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/pizzeria
  #    username: postgres
  #    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update


  #liquibase:
  #  change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 9096
  servlet:
    context-path: /
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 15m





