spring:
  application:
    name: registration-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizzeria
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080
  servlet:
    context-path: /
#jwt:
#  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
#  lifetime: 20m


logging:
  level:
    root: WARN
    org.aston.registrationservice: INFO
  file:
    name: by.nata
    path: /

#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/pizzeria?createDatabaseIfNotExist=true
#      username: user
#      password: user