version: '3.8'
services:
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "9095:9095"
    depends_on:
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orders
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - POSTGRES_DRIVER=org.postgresql.Driver

  order-db:
    image: postgres:14-alpine
    container_name: order-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DRIVER=org.postgresql.Driver